import Head from 'next/head'
import { Box, Grid, Container, Button, Typography, useTheme,Card } from '@mui/material'
import LocationOnIcon from '@mui/icons-material/LocationOn';
import Image from 'next/image'
import delivery from '../public/img/delivery.svg'
import FoodRow from '../components/FoodRow';
import React,{ useEffect } from 'react';
import { getAllItems } from '../utils/firebaseFunctions';
export default function Home() {

  const theme = useTheme()

  return (
    <Box sx={{}}>
      <Head>
        <title>Food Master</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/img/appLogo.png" />
      </Head>

      <Box sx={{mb:5}}>
        <Container sx={{}} maxWidth="xl">
          <Grid container sx={{ minHeight: "92vh" }}>
            <Grid item xs={12} md={6} sx={{ display: "flex", alignItems: "center" }}>
              <Container sx={{ mt: 5 }}>
                <Button variant="outlined" sx={{ mb: 5 }}>
                  <LocationOnIcon sx={{ mx: 1 }} /> <span>Kamayut, Yangon , Myanmar</span>
                </Button>
                <Typography sx={{ fontSize: "40px", mt: 3 }} variant="h1">
                  The fastest food delivery service <span style={{ color: theme.palette.primary.dark }}>in Yangon </span>
                </Typography>
                <Typography sx={{ fontSize: "15px", mb: 5, fontStyle: "italic" }} variant="h3">
                  Get the best sevices with minimum cost
                </Typography>
                <Typography sx={{ mb: 5 }} variant="p">
                  Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
                </Typography>
                <Box sx={{ mt: 3 }}>
                  <Button sx={{ mr: 1 }} variant="contained">
                    Order Now
                  </Button>
                  <Button variant="outlined">
                    About us
                  </Button>
                </Box>
              </Container>
            </Grid>
            <Grid item xs={12} md={6} sx={{ display: "flex", alignItems: "center" }}>
              <Container sx={{ width: "80%" }}>
                <Image src={delivery} alt={"ok"} />
              </Container>
            </Grid>
          </Grid>
        </Container>
      </Box>

      <FoodRow/>
      

    </Box>
  )
}
